allowBuilds:
  bufferutil: set this to true or false
  core-js: set this to true or false
  es5-ext: set this to true or false
  sharp: false
  unrs-resolver: false
  utf-8-validate: set this to true or false
